concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{
    github.event.pull_request.id }}
env:
  LANG: en_US.UTF-8
jobs:
  build-jdk17:
    if: github.repository != 'quarkusio/quarkus'
    name: Quick JDK 17 Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Reclaim Disk Space
      run: .github/ci-prerequisites.sh
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      id: get-date
      name: Get Date
      run: 'echo "date=$(/bin/date -u "+%Y-%m")" >> $GITHUB_OUTPUT

        '
      shell: bash
    - continue-on-error: true
      id: cache-maven
      name: Cache Maven Repository
      uses: actions/cache@v4
      with:
        key: q2maven-${{ steps.get-date.outputs.date }}
        path: ~/.m2/repository
    - continue-on-error: true
      if: steps.cache-maven.outputs.cache-hit != 'true'
      name: Build
      run: './mvnw -T1C -e -B --settings .github/mvn-settings.xml -Dquickly-ci -Dtcks
        clean install

        '
    - continue-on-error: true
      if: steps.cache-maven.outputs.cache-hit != 'true'
      name: Delete Local Artifacts From Cache
      run: rm -r ~/.m2/repository/io/quarkus
      shell: bash
name: Quarkus CI Fork Maven Cache
on:
  repository_dispatch:
    types: trigger-ga___ci-fork-mvn-cache.yml
