env:
  MAVEN_ARGS: -B -e
jobs:
  cache:
    if: github.repository == 'quarkusio/quarkus' || github.event_name == 'workflow_dispatch'
    name: Build and save artifacts
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Install artifacts
      run: ./mvnw ${MAVEN_ARGS} -DskipTests -DskipITs -Dinvoker.skip clean install
        -pl :quarkus-integration-test-istio-invoker -am
    - continue-on-error: true
      name: Tar Maven repository
      run: tar -I 'pigz -9' -cf maven-repo.tgz -C ~ .m2/repository
      shell: bash
    - continue-on-error: true
      name: Persist Maven repository
      uses: actions/upload-artifact@v4
      with:
        name: maven-repo
        path: maven-repo.tgz
        retention-days: 1
  kubernetes:
    if: github.repository == 'quarkusio/quarkus' || github.event_name == 'workflow_dispatch'
    name: Istio + Kubernetes Integration Tests
    needs: cache
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Download Maven repository
      uses: actions/download-artifact@v4
      with:
        name: maven-repo
        path: .
    - continue-on-error: true
      name: Extract Maven repository
      run: tar -xzf maven-repo.tgz -C ~
      shell: bash
    - continue-on-error: true
      name: Set up Minikube-Kubernetes
      uses: manusa/actions-setup-minikube@v2.11.0
      with:
        github token: ${{ secrets.GITHUB_TOKEN }}
        kubernetes version: ${{ matrix.kubernetes }}
        minikube version: v1.16.0
        start args: --embed-certs --addons=metrics-server --force
    - continue-on-error: true
      name: Quay login
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.QUAY_QUARKUSCI_PASSWORD }}
        registry: quay.io
        username: ${{ secrets.QUAY_QUARKUSCI_USERNAME }}
    - continue-on-error: true
      id: kubeconfig
      name: Get kubeconfig
      run: a="$(cat ~/.kube/config)"; a="${a//'%'/'%25'}"; a="${a//$'\n'/'%0A'}";
        a="${a//$'\r'/'%0D'}"; echo "config=$a" >> $GITHUB_OUTPUT
    - continue-on-error: true
      name: Install Istio
      uses: huang195/actions-install-istio@v1.0.0
      with:
        istio version: 1.15.2
        kubeconfig: ${{steps.kubeconfig.outputs.config}}
    - continue-on-error: true
      name: Run Istio Invoker Tests
      run: 'export QUARKUS_CONTAINER_IMAGE_GROUP=quarkustesting

        export QUARKUS_CONTAINER_IMAGE_TAG=${{ github.sha }}

        export QUARKUS_CONTAINER_IMAGE_REGISTRY=quay.io

        ./mvnw ${MAVEN_ARGS} clean install -pl :quarkus-integration-test-istio-invoker
        -De2e-tests -Dkubernetes-e2e-tests

        '
    - continue-on-error: true
      if: always() && github.repository == 'quarkusio/quarkus'
      name: Report status
      run: "curl -Ls https://sh.jbang.dev | bash -s - app setup\n~/.jbang/bin/jbang\
        \ .github/NativeBuildReport.java \\\n  issueNumber=29536 \\\n  runId=${{ github.run_id\
        \ }} \\\n  status=${{ job.status }} \\\n  token=${{ secrets.GITHUB_API_TOKEN\
        \ }} \\\n  issueRepo=${{ github.repository }} \\\n  thisRepo=${{ github.repository\
        \ }}\n"
      shell: bash
    strategy:
      fail-fast: false
      matrix:
        kubernetes:
        - v1.20.1
name: Quarkus CI - Istio
on:
  repository_dispatch:
    types: trigger-ga___ci-istio.yml
