env:
  MAVEN_ARGS: -B -e
jobs:
  cache:
    if: github.repository == 'quarkusio/quarkus' || github.event_name == 'workflow_dispatch'
    name: Build and save artifacts
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Install artifacts
      run: ./mvnw ${MAVEN_ARGS} -DskipTests -DskipITs -Dinvoker.skip clean install
        -pl :quarkus-integration-test-kubernetes-invoker -am
    - continue-on-error: true
      name: Tar Maven repository
      run: tar -I 'pigz -9' -cf maven-repo.tgz -C ~ .m2/repository
      shell: bash
    - continue-on-error: true
      name: Persist Maven repository
      uses: actions/upload-artifact@v4
      with:
        name: maven-repo
        path: maven-repo.tgz
        retention-days: 1
  knative:
    if: github.repository == 'quarkusio/quarkus' || github.event_name == 'workflow_dispatch'
    name: Knative Integration Tests
    needs: cache
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Download Maven repository
      uses: actions/download-artifact@v4
      with:
        name: maven-repo
        path: .
    - continue-on-error: true
      name: Extract Maven repository
      run: tar -xzf maven-repo.tgz -C ~
      shell: bash
    - continue-on-error: true
      name: Kubernetes KinD Cluster
      uses: container-tools/kind-action@v2
      with:
        knative_serving: ${{ matrix.knative }}
        kubectl_version: ${{ matrix.kubernetes }}
        registry: true
        version: v0.11.1
    - continue-on-error: true
      name: Run Knative Invoker Tests
      run: 'kubectl create namespace knative-tests

        kubectl config set-context --current --namespace=knative-tests

        export QUARKUS_CONTAINER_IMAGE_GROUP=quarkustesting

        export QUARKUS_CONTAINER_IMAGE_TAG=${{ github.sha }}

        export QUARKUS_CONTAINER_IMAGE_REGISTRY=$KIND_REGISTRY

        export QUARKUS_CONTAINER_IMAGE_INSECURE=true

        ./mvnw ${MAVEN_ARGS} clean install -pl :quarkus-integration-test-kubernetes-invoker
        -De2e-tests -Dknative-e2e-tests

        '
    - continue-on-error: true
      if: always() && github.repository == 'quarkusio/quarkus'
      name: Report status
      run: "curl -Ls https://sh.jbang.dev | bash -s - app setup\n~/.jbang/bin/jbang\
        \ .github/NativeBuildReport.java \\\n  issueNumber=31837 \\\n  runId=${{ github.run_id\
        \ }} \\\n  status=${{ job.status }} \\\n  token=${{ secrets.GITHUB_API_TOKEN\
        \ }} \\\n  issueRepo=${{ github.repository }} \\\n  thisRepo=${{ github.repository\
        \ }}\n"
      shell: bash
    strategy:
      fail-fast: false
      matrix:
        knative:
        - v1.2.0
        kubernetes:
        - v1.20.1
  kubernetes:
    if: github.repository == 'quarkusio/quarkus' || github.event_name == 'workflow_dispatch'
    name: Kubernetes Integration Tests
    needs: cache
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Download Maven repository
      uses: actions/download-artifact@v4
      with:
        name: maven-repo
        path: .
    - continue-on-error: true
      name: Extract Maven repository
      run: tar -xzf maven-repo.tgz -C ~
      shell: bash
    - continue-on-error: true
      name: Set up Minikube-Kubernetes
      uses: manusa/actions-setup-minikube@v2.11.0
      with:
        github token: ${{ secrets.GITHUB_TOKEN }}
        kubernetes version: ${{ matrix.kubernetes }}
        minikube version: v1.16.0
        start args: --addons=metrics-server --force
    - continue-on-error: true
      name: Quay login
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.QUAY_QUARKUSCI_PASSWORD }}
        registry: quay.io
        username: ${{ secrets.QUAY_QUARKUSCI_USERNAME }}
    - continue-on-error: true
      name: Run Kubernetes Invoker Tests
      run: 'export QUARKUS_CONTAINER_IMAGE_GROUP=quarkustesting

        export QUARKUS_CONTAINER_IMAGE_TAG=${{ github.sha }}

        export QUARKUS_CONTAINER_IMAGE_REGISTRY=quay.io

        ./mvnw ${MAVEN_ARGS} clean install -pl :quarkus-integration-test-kubernetes-invoker
        -De2e-tests -Dkubernetes-e2e-tests

        '
    - continue-on-error: true
      if: always() && github.repository == 'quarkusio/quarkus'
      name: Report status
      run: "curl -Ls https://sh.jbang.dev | bash -s - app setup\n~/.jbang/bin/jbang\
        \ .github/NativeBuildReport.java \\\n  issueNumber=26581 \\\n  runId=${{ github.run_id\
        \ }} \\\n  status=${{ job.status }} \\\n  token=${{ secrets.GITHUB_API_TOKEN\
        \ }} \\\n  issueRepo=${{ github.repository }} \\\n  thisRepo=${{ github.repository\
        \ }}\n"
      shell: bash
    strategy:
      fail-fast: false
      matrix:
        kubernetes:
        - v1.20.1
  openshift:
    if: github.repository == 'quarkusio/quarkus' || github.event_name == 'workflow_dispatch'
    name: OpenShift Integration Tests
    needs: cache
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Download Maven repository
      uses: actions/download-artifact@v4
      with:
        name: maven-repo
        path: .
    - continue-on-error: true
      name: Extract Maven repository
      run: tar -xzf maven-repo.tgz -C ~
      shell: bash
    - continue-on-error: true
      name: Set up OpenShift
      uses: manusa/actions-setup-openshift@v1.1.5
      with:
        github token: ${{ secrets.GITHUB_TOKEN }}
        oc version: ${{ matrix.openshift }}
    - continue-on-error: true
      name: Quay login
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.QUAY_QUARKUSCI_PASSWORD }}
        registry: quay.io
        username: ${{ secrets.QUAY_QUARKUSCI_USERNAME }}
    - continue-on-error: true
      name: Run OpenShift Invoker Tests
      run: 'export QUARKUS_CONTAINER_IMAGE_GROUP=quarkustesting

        export QUARKUS_CONTAINER_IMAGE_TAG=${{ github.sha }}

        export QUARKUS_CONTAINER_IMAGE_REGISTRY=quay.io

        export QUARKUS_CONTAINER_IMAGE_USERNAME=${{ secrets.QUAY_QUARKUSCI_USERNAME
        }}

        export QUARKUS_CONTAINER_IMAGE_PASSWORD=${{ secrets.QUAY_QUARKUSCI_PASSWORD
        }}

        ./mvnw ${MAVEN_ARGS} clean install -pl :quarkus-integration-test-kubernetes-invoker
        -De2e-tests -Dopenshift-e2e-tests

        '
    - continue-on-error: true
      if: always() && github.repository == 'quarkusio/quarkus'
      name: Report status
      run: "curl -Ls https://sh.jbang.dev | bash -s - app setup\n~/.jbang/bin/jbang\
        \ .github/NativeBuildReport.java \\\n  issueNumber=26582 \\\n  runId=${{ github.run_id\
        \ }} \\\n  status=${{ job.status }} \\\n  token=${{ secrets.GITHUB_API_TOKEN\
        \ }} \\\n  issueRepo=${{ github.repository }} \\\n  thisRepo=${{ github.repository\
        \ }}\n"
      shell: bash
    strategy:
      fail-fast: false
      matrix:
        openshift:
        - v3.11.0
name: Quarkus CI - Kubernetes
on:
  repository_dispatch:
    types: trigger-ga___ci-kubernetes.yml
