env:
  LANG: en_US.UTF-8
jobs:
  build-and-deploy:
    env:
      MAVEN_OPTS: -Xmx2048m -XX:MaxMetaspaceSize=1000m
    if: github.repository == 'quarkusio/quarkus'
    name: Build and deploy
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        ref: main
    - continue-on-error: true
      name: Reclaim Disk Space
      run: .github/ci-prerequisites.sh
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      id: get-date
      name: Get Date
      run: 'echo "date=$(/bin/date -u "+%Y-%m")" >> $GITHUB_OUTPUT

        '
      shell: bash
    - continue-on-error: true
      id: cache-maven
      name: Cache Maven Repository
      uses: actions/cache@v4
      with:
        key: deploy-snapshots-${{ steps.get-date.outputs.date }}
        path: ~/.m2/repository
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
      name: Build and Deploy
      run: "./mvnw -e -B --settings .github/mvn-settings.xml \\\n  -DskipTests -DskipITs\
        \ -Dno-format -Dinvoker.skip=true \\\n  -DretryFailedDeploymentCount=10 \\\
        \n  -Dno-test-modules \\\n  -Dgradle.cache.local.enabled=false \\\n  -Ddokka\
        \ \\\n  -Prelocations \\\n  clean deploy\n"
    - continue-on-error: true
      name: Delete Local Artifacts From Cache
      run: rm -r ~/.m2/repository/io/quarkus
      shell: bash
    - continue-on-error: true
      if: always()
      name: Report
      run: "curl -Ls https://sh.jbang.dev | bash -s - app setup\n~/.jbang/bin/jbang\
        \ .github/NativeBuildReport.java \\\n  issueNumber=12111 \\\n  runId=${{ github.run_id\
        \ }} \\\n  status=${{ job.status }} \\\n  token=${{ secrets.GITHUB_API_TOKEN\
        \ }} \\\n  issueRepo=${{ github.repository }} \\\n  thisRepo=${{ github.repository\
        \ }}\n"
      shell: bash
name: Quarkus Deploy Snapshots
on:
  repository_dispatch:
    types: trigger-ga___deploy-snapshots.yml
