defaults:
  run:
    shell: bash
jobs:
  publish-build-scans:
    if: github.repository == 'quarkusio/quarkus' && github.event.workflow_run.event
      == 'pull_request' && github.event.workflow_run.conclusion != 'cancelled'
    permissions:
      actions: write
      checks: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: setup
      name: Setup Build Scan link capture
      uses: gradle/develocity-actions/maven-setup@v1
      with:
        add-job-summary: true
        add-pr-comment: false
    - continue-on-error: true
      id: publish
      name: Publish Maven Build Scans
      uses: gradle/develocity-actions/maven-publish-build-scan@v1
      with:
        develocity-access-key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
        develocity-url: https://ge.quarkus.io
    - continue-on-error: true
      name: Output JSON file
      run: "if [ -f \"${{ steps.setup.outputs.build-metadata-file-path }}\" ]; then\n\
        \  echo \"```json\" >> $GITHUB_STEP_SUMMARY\n  jq '.' ${{ steps.setup.outputs.build-metadata-file-path\
        \ }} >> $GITHUB_STEP_SUMMARY\n  echo \"\\n```\" >> $GITHUB_STEP_SUMMARY;\n\
        fi\n"
    - continue-on-error: true
      name: Inject build scans in reports
      uses: quarkusio/action-helpers@main
      with:
        action: inject-build-scans
        build-metadata-file-path: ${{ steps.setup.outputs.build-metadata-file-path
          }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        workflow-run-id: ${{ github.event.workflow_run.id }}
name: Develocity - Publish Maven Build Scans
on:
  repository_dispatch:
    types: trigger-ga___develocity-publish-build-scans.yml
