concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository
    != 'quarkusio/quarkus' }}
  group: workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{
    github.event.pull_request.id }}
jobs:
  build-doc:
    if: github.repository == 'quarkusio/quarkus' || !endsWith(github.ref, '/main')
    name: Documentation Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      id: get-date
      name: Get Date
      run: 'echo "date=$(/bin/date -u "+%Y-%m")" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      id: cache-maven
      name: Cache Maven Repository
      uses: actions/cache@v4
      with:
        key: q2maven-doc-${{ steps.get-date.outputs.date }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Build
      run: './mvnw -DquicklyDocs -B --settings .github/mvn-settings.xml

        '
    - continue-on-error: true
      name: Build Docs
      run: "if ./mvnw -e -B --settings .github/mvn-settings.xml clean package -pl\
        \ docs -Dasciidoctor.fail-if=DEBUG ; then\n  echo \"Build ok\"\nelse\n  if\
        \ [ -f docs/target/metadataErrors.md ]; then\n    echo \"### Document Metadata\
        \ Errors\" >> $GITHUB_STEP_SUMMARY\n    cat docs/target/metadataErrors.md\
        \ >> $GITHUB_STEP_SUMMARY\n  fi\n  exit 1\nfi\n"
    - continue-on-error: true
      name: Store PR id
      run: echo ${{ github.event.number }} > pr-id.txt
    - continue-on-error: true
      name: Persist documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: 'pr-id.txt

          docs/

          target/asciidoc/generated/config/

          '
        retention-days: 1
    timeout-minutes: 60
  ci-sanity-check:
    name: CI Sanity Check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Build
      run: sleep 30
name: Quarkus Documentation CI
on:
  repository_dispatch:
    types: trigger-ga___doc-build.yml
