concurrency:
  cancel-in-progress: ${{ github.event_name == 'issues' || github.repository != 'quarkusio/quarkus'
    }}
  group: workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, issue =
    ${{ github.event.issue.id }}
jobs:
  autolabel:
    if: github.repository == 'quarkusio/quarkus'
    name: auto label
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        BOTNAME: quarkusbot
        EPICLABEL: kind/epic
        GITHUB_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
      name: epicmaker
      uses: docker://maxandersen/jbang-epic-maker
name: Epic issue lists
on:
  repository_dispatch:
    types: trigger-ga___epicissues.yml
