env:
  DB_NAME: hibernate_orm_test
  DB_PASSWORD: hibernate_orm_test
  DB_USER: hibernate_orm_test
  JVM_TEST_MAVEN_OPTS: -e -B --settings .github/mvn-settings.xml -Dtest-containers
    -Dstart-containers -Dtest-resteasy-reactive-large-files -Dformat.skip
  LANG: en_US.UTF-8
  MAVEN_OPTS: -Xmx2g -XX:MaxMetaspaceSize=1g
jobs:
  linux-jvm-test:
    env:
      MAVEN_OPTS: -Xmx2048m -XX:MaxMetaspaceSize=1000m
    if: github.repository == 'quarkusio/quarkus' || github.event_name == 'workflow_dispatch'
    name: JVM Tests - Early Access JDK ${{ matrix.version }} Build - ${{ matrix.dist
      }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: matrix.dist == 'jdk.java.net'
      name: Set up JDK from jdk.java.net
      uses: oracle-actions/setup-java@v1
      with:
        release: ${{ matrix.version }}
        website: jdk.java.net
    - continue-on-error: true
      if: matrix.dist != 'jdk.java.net'
      name: Set up JDK from other provider than jdk.java.net
      uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.dist }}
        java-version: ${{ matrix.version }}
    - continue-on-error: true
      name: Print Java version
      run: java -version
      shell: bash
    - continue-on-error: true
      name: Stop mysql
      run: 'ss -ln

        sudo service mysql stop || true

        '
      shell: bash
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'workflow_dispatch' && github.event.ref || 'main'
          }}
    - continue-on-error: true
      name: Reclaim Disk Space
      run: .github/ci-prerequisites.sh
    - continue-on-error: true
      id: get-date
      name: Get Date
      run: 'echo "date=$(/bin/date -u "+%Y-%m")" >> $GITHUB_OUTPUT

        '
      shell: bash
    - continue-on-error: true
      id: cache-maven
      name: Cache Maven Repository
      uses: actions/cache@v4
      with:
        key: q2maven-${{ steps.get-date.outputs.date }}-${{ matrix.version }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Build with Maven
      run: './mvnw $JVM_TEST_MAVEN_OPTS -Dtcks install -fae

        '
    - continue-on-error: true
      if: failure()
      name: Prepare failure archive (if maven failed)
      run: find . -name '*-reports' -type d -o -name '*.log' | tar -czf test-reports.tgz
        -T -
      shell: bash
    - continue-on-error: true
      if: failure()
      name: Upload failure Archive (if maven failed)
      uses: actions/upload-artifact@v4
      with:
        name: test-reports-linux-jvm${{ matrix.version }}
        path: test-reports.tgz
    - continue-on-error: true
      if: always()
      name: Delete Local Artifacts From Cache
      run: rm -r ~/.m2/repository/io/quarkus
      shell: bash
    - continue-on-error: true
      if: always() && github.repository == 'quarkusio/quarkus' && github.event_name
        != 'workflow_dispatch'
      name: Report status
      run: "curl -Ls https://sh.jbang.dev | bash -s - app setup\n~/.jbang/bin/jbang\
        \ .github/NativeBuildReport.java \\\n  issueNumber=15867 \\\n  runId=${{ github.run_id\
        \ }} \\\n  status=${{ job.status }} \\\n  token=${{ secrets.GITHUB_API_TOKEN\
        \ }} \\\n  issueRepo=${{ github.repository }} \\\n  thisRepo=${{ github.repository\
        \ }}\n"
      shell: bash
    strategy:
      fail-fast: false
      matrix: "${{\n  fromJSON(\n    github.event_name == 'workflow_dispatch'\n  \
        \  && format( '{{ \"include\": [{{ \"version\": \"{0}\", \"dist\": \"{1}\"\
        \ }}] }}',\n        github.event.inputs.jdkVersion, github.event.inputs.jdkDistribution\
        \ )\n    || '{ \"include\": [{ \"version\": 20, \"dist\": \"jdk.java.net\"\
        \ }, { \"version\": 21, \"dist\": \"jdk.java.net\" }] }'\n  )\n}}"
    timeout-minutes: 360
name: Quarkus Early Access JDK Build
on:
  repository_dispatch:
    types: trigger-ga___jdk-early-access-build.yml
