jobs:
  owasp:
    if: github.repository == 'quarkusio/quarkus'
    name: OWASP Dependency Check Report
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        ref: main
    - continue-on-error: true
      name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build Java
      run: ./mvnw -B --settings .github/mvn-settings.xml -Dquickly-ci install
    - continue-on-error: true
      name: Perform OWASP Dependency Check Report
      run: ./mvnw -Dowasp-report
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: target/dependency-check-report.html
        retention-days: 5
    strategy:
      fail-fast: false
name: OWASP Dependency Check
on:
  repository_dispatch:
    types: trigger-ga___owasp-check.yml
