defaults:
  run:
    shell: bash
jobs:
  preview:
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion
      == 'success'
    permissions:
      actions: read
      issues: write
      pull-requests: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 5000
        fetch-tags: false
        repository: quarkusio/quarkusio.github.io
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        path: quarkus-main
        repository: quarkusio/quarkus
    - continue-on-error: true
      name: Install git-restore-time
      run: sudo apt-get install -y git-restore-mtime
    - continue-on-error: true
      name: Restore mtime
      run: git restore-mtime
    - continue-on-error: true
      name: Download PR Artifact
      uses: actions/download-artifact@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        name: documentation
        path: documentation-temp
        run-id: ${{ github.event.workflow_run.id }}
    - continue-on-error: true
      id: pr
      name: Store PR id as variable
      run: "pr=$(<documentation-temp/pr-id.txt)\nif ! [[ $pr =~ ^[0-9]+$ ]] ; then\n\
        \  echo \"PR id extracted from documentation-temp/pr-id.txt is not a number:\
        \ $pr\"\n  exit 1\nfi\necho \"id=$(<documentation-temp/pr-id.txt)\" >> $GITHUB_OUTPUT\n"
    - continue-on-error: true
      name: Sync documentation
      run: 'rm ./documentation-temp/docs/sync-web-site.sh

        cp -a ./quarkus-main/docs/sync-web-site.sh ./documentation-temp/docs/

        chmod 755 ./documentation-temp/docs/sync-web-site.sh

        ./documentation-temp/docs/sync-web-site.sh main ../../

        rm -rf documentation-temp

        rm -rf quarkus-main

        '
      shell: bash
    - continue-on-error: true
      name: Set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.3
    - continue-on-error: true
      name: Build Jekyll site
      uses: limjh16/jekyll-action-ts@v2
      with:
        custom_opts: --config _config.yml,_only_latest_guides_config.yml
        enable_cache: true
        format_output: false
        prettier_ignore: '*'
    - continue-on-error: true
      name: Reduce the size of the website to be compatible with surge
      run: 'find assets/images/posts/ -mindepth 1 -maxdepth 1 -type d -mtime +100
        -exec rm -rf _site/{} \;

        find newsletter/ -mindepth 1 -maxdepth 1 -type d -mtime +100 -exec rm -rf
        _site/{} \;

        rm -rf _site/assets/images/worldtour/2023

        rm -rf _site/assets/images/desktopwallpapers

        '
    - continue-on-error: true
      env:
        PR_ID: ${{ steps.pr.outputs.id }}
      id: deploy
      name: Publishing to surge for preview
      run: npx surge ./_site --domain https://quarkus-pr-main-${PR_ID}-preview.surge.sh
        --token ${{ secrets.SURGE_TOKEN }}
    - continue-on-error: true
      name: Update PR status comment on success
      uses: actions-cool/maintain-one-comment@v3.2.0
      with:
        body: "\U0001F38A PR Preview ${{ github.sha }} has been successfully built\
          \ and deployed to https://quarkus-pr-main-${{ steps.pr.outputs.id }}-preview.surge.sh/version/main/guides/\n\
          \n- Images of blog posts older than 3 months are not available.\n- Newsletters\
          \ older than 3 months are not available.\n\n<img width=\"300\" src=\"https://user-images.githubusercontent.com/507615/90250366-88233900-de6e-11ea-95a5-84f0762ffd39.png\"\
          >\n<!-- Sticky Pull Request Comment -->\n"
        body-include: <!-- Sticky Pull Request Comment -->
        number: ${{ steps.pr.outputs.id }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      if: ${{ failure() }}
      name: Update PR status comment on failure
      uses: actions-cool/maintain-one-comment@v3.2.0
      with:
        body: "\U0001F62D Deploy PR Preview failed.\n<img width=\"300\" src=\"https://user-images.githubusercontent.com/507615/90250824-4e066700-de6f-11ea-8230-600ecc3d6a6b.png\"\
          >\n<!-- Sticky Pull Request Comment -->\n"
        body-include: <!-- Sticky Pull Request Comment -->
        number: ${{ steps.pr.outputs.id }}
        token: ${{ secrets.GITHUB_TOKEN }}
name: Surge.sh Preview
on:
  repository_dispatch:
    types: trigger-ga___preview.yml
