jobs:
  lint:
    name: quarkus-github-bot.yml validation
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: install yamllint
      run: sudo apt-get install -y yamllint
      shell: bash
    - continue-on-error: true
      name: run yamllint for quarkus-github-bot.yml
      run: yamllint -c .github/yamllint.conf .github/quarkus-github-bot.yml
      shell: bash
name: quarkus-github-bot.yml lint
on:
  repository_dispatch:
    types: trigger-ga___quarkus-github-bot-lint.yml
