concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository
    != 'quarkusio/quarkus' }}
  group: workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{
    github.event.pull_request.id }}
jobs:
  vale:
    name: Linting with Vale
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      name: Vale Linter
      uses: errata-ai/vale-action@reviewdog
      with:
        fail_on_error: false
        files: docs/src/main/asciidoc/
        filter_mode: diff_context
        vale_flags: --no-exit --config=docs/.vale.ini
name: Linting with Vale
on:
  repository_dispatch:
    types: trigger-ga___vale.yml
